[package]
name = "cyan-skillfish-governor-smu"
version = "0.2.0"
license = "MIT"
edition = "2024"

[dependencies]
libdrm_amdgpu_sys = "0.8.8"
toml = "0.9.5"
nix = { version = "0.29", features = ["fs"] }
thiserror = "1.0"
