# us
[timing.intervals]
sample = 250
adjust = 100_000

# MHz/ms
[timing.ramp-rates]
normal = 1
burst = 50

# number of samples
[timing]
burst-samples = 50
down-events = 5

# MHz
[frequency-thresholds]
adjust = 50

# %
[load-target]
upper = 0.75
lower = 0.50

#Â°C
[temperature]
throttling = 85
throttling_recovery = 75

[[safe-points]]
frequency = 400
voltage = 700

[[safe-points]]
frequency = 1175
voltage = 700

[[safe-points]]
frequency = 1400
voltage = 750

[[safe-points]]
frequency = 1600
voltage = 800

[[safe-points]]
frequency = 1700
voltage = 850

[[safe-points]]
frequency = 1850
voltage = 900

[[safe-points]]
frequency = 2000
voltage = 950

[[safe-points]]
frequency = 2050
voltage = 975

[[safe-points]]
frequency = 2100
voltage = 1000

[[safe-points]]
frequency = 2125
voltage = 1015

[[safe-points]]
frequency = 2150
voltage = 1025

[[safe-points]]
frequency = 2200
voltage = 1045

[[safe-points]]
frequency = 2230
voltage = 1075

[[safe-points]]
frequency = 2300
voltage = 1100

[[safe-points]]
frequency = 2350
voltage = 1125


