# us
[timing.intervals]
sample = 2000
adjust = 500_000
finetune = 1_000_000

# MHz/ms
[timing.ramp-rates]
normal = 50
burst = 100

# number of samples
[timing]
burst-samples = 48

# MHz
[frequency-thresholds]
adjust = 100
finetune = 10

[load-target]
upper = 0.70
lower = 0.45


[temperature]
throttling = 85
throttling_recovery = 75

[[safe-points]]
frequency = 350
voltage = 700

[[safe-points]]
frequency = 500
voltage = 700

[[safe-points]]
frequency = 1175
voltage = 700

[[safe-points]]
frequency = 1400
voltage = 750

[[safe-points]]
frequency = 1600
voltage = 800

[[safe-points]]
frequency = 1700
voltage = 850

[[safe-points]]
frequency = 1850
voltage = 900

[[safe-points]]
frequency = 2000
voltage = 950

[[safe-points]]
frequency = 2050
voltage = 975

[[safe-points]]
frequency = 2100
voltage = 1000

[[safe-points]]
frequency = 2125
voltage = 1015

[[safe-points]]
frequency = 2150
voltage = 1025

[[safe-points]]
frequency = 2200
voltage = 1045

[[safe-points]]
frequency = 2230
voltage = 1055
