# us
[timing.intervals]
sample = 500
adjust = 200_000

# MHz/ms
[timing.ramp-rates]
normal = 1
burst = 50

# number of samples
[timing]
burst-samples = 60
down-events = 5

# MHz
[frequency-thresholds]
adjust = 10

# %
[load-target]
upper = 0.80
lower = 0.65

#Â°C
[temperature]
throttling = 85
throttling_recovery = 75

[[safe-points]]
frequency = 1000
voltage = 800

[[safe-points]]
frequency = 1175
voltage = 850

[[safe-points]]
frequency = 1500
voltage = 900

[[safe-points]]
frequency = 1600
voltage = 910

[[safe-points]]
frequency = 1700
voltage = 920

[[safe-points]]
frequency = 1850
voltage = 930

[[safe-points]]
frequency = 2000
voltage = 960

[[safe-points]]
frequency = 2050
voltage = 980

[[safe-points]]
frequency = 2100
voltage = 1000

[[safe-points]]
frequency = 2125
voltage = 1020

[[safe-points]]
frequency = 2150
voltage = 1035

[[safe-points]]
frequency = 2200
voltage = 1050

